name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26'
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -ldflags "-s -w -X main.Version=${{ github.event.release.tag_name }}" -o sdtd_client main.go

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: sdtd_client
          name: ${{ github.event.release.name }}
          tag_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          generate_release_notes: true
